### ISSUE TITLE
如何应用这个到cloudflare

### ISSUE THREAD

**Issue by Tiger-zero** [NekoChanTaiwan/NekoChan-Open-Data#2]
如题，我觉得你这个fork修改的非常好，我也想应用试试，就是不知道怎么应用你这个项目 是否能给出安装和使用说明?

**Comment by aaronlin0122** [comment]
和其他人魔改的安裝方式一樣，版本填最新的min版本即可。

**Comment by aaronlin0122** [comment]
已補上 安裝 & 使用 。
https://github.com/NekoChanTaiwan/NekoChan-Open-Data/blob/master/README.md
